### ISSUE TITLE
Do you guys have a screen flicker problem after sleep with 4k screen?

### ISSUE THREAD

**Issue by soulomoon** [wmchris/DellXPS15-9550-OSX#24]
It seems that most laptop with 4k screen, would flicker after sleep.
I tested it, not an issue with sleeping, but what ever you do to shut down the screen.
E.g.
If I connect my screen to an extra screen, 
then I close my laptop,
the extra screen is normally open, being said, it is not sleeping.
then I open my laptop,
there is high chance that my builtin screen would start flickering for now and then.
and have to restart to fix it.

Being in this bug, that I won't be able to put my laptop in sleep or just simply close my laptop.
Really hoping to get some enlightening if there is any.

**Comment by wmchris** [comment]
sorry, this is the first time i heard of it, and i have a 4k for myself.

**Comment by HeavenVolkoff** [comment]
I can confirm this. I have a 4k 9550, and after sleep, sometimes, my screen stars flickering, and even shut down. However, most times, I can fix this by putting the laptop to sleep again.

**Comment by wmchris** [comment]
is this really a mac os problem or does it also occur on windows?

**Comment by HeavenVolkoff** [comment]
No, it is exclusive to macOS. Neither with Windows nor with Ubuntu/Fedora I have experienced this issue.

**Comment by deecewan** [comment]
This has been an issue with this laptop since the beginning.  Apparently it's a problem with the PWM from the BIOS, and the only way to fix it will be with an update to the BIOS.

Only happens under hackintosh. If your screen does not flicker after sleep, consider yourself lucky.

**Comment by soulomoon** [comment]
@wmchris @HeavenVolkoff @deecewan @Lockzi 
Seems that using [darkhand clover config](https://github.com/darkhandz/XPS15-9550-High-Sierra)
and change the ig-platform-id from 0x191B0000 to 0x19160000 fix the problem, in both 10.12.6 and high sierra 10.13.1.
[take a look here](https://github.com/darkhandz/XPS15-9550-High-Sierra/issues/24)

**Comment by krim404** [comment]
can someone check this fix? I dont have the flicker problem at all on my machine, so i cant see if this has any drawbacks

**Comment by HeavenVolkoff** [comment]
Tried, but the flicker continued the same here. Maybe darkhandz's config have something else that I am missing... Will look into it later....

**Comment by maguanghui** [comment]
I also have this problem and
try solumoon’s way but it
 do not work. I think the problem is occurred by coredisplayfixup.kext.

**Comment by soulomoon** [comment]
It seems the fix is limited to my machine,
My machine specific:
cpu&gpu: i7-6820HG , HD530
bios: 1.5.1

And since it may be a bios related problem,
Is it related to bios setting too?

@maguanghui 
coredisplayfixup.kext does not seem to be a problem in my machine.

**Comment by krim404** [comment]
is it possible that you simply do not see the flicker on darkhands files? i patched the applebacklight to reduce the minimum brightness to 3%, while darkhands is limited to somewhat about 10%. obviously if you have a pwm flicker, it will flicker very strong on a lower brightness....

**Comment by maguanghui** [comment]
but it just flicker after sleep and  nothing to do with brightness.

**Comment by soulomoon** [comment]
@wmchris 
I don't think it is the pwm flicker. it is not the mild constant flicker, but more intense, in inconstant rate.
The flicker causes the screen redraw itself, and is accompany with white lines in the screen sometimes, like the screen is being interfere by some electrical signal, only happens after the screen shuts down and turns on(aka sleep and wake or close and open lid).

And with darkhands files, if I don't change the ig-platform-id, the problem would still exist.

**Comment by krim404** [comment]
ah. first time i really understand the problem.
but here i'm completly dependent on your findings, because on none of my machines i can reproduce this behaviour.

**Comment by jhlee8804** [comment]
+1

My environment)
BIOS: 1.5.1
OS: macOS Sierra 10.12.6
CPU: i7-6700HQ,
GPU: HD530

**Comment by krim404** [comment]
@jhlee8804 +1 = you have the issue, or it resolved your issue?

**Comment by jhlee8804** [comment]
@wmchris I'v issue too. Here is my video.
https://drive.google.com/file/d/1xbc17sceeJl3_DWIAc4RV8PLwDmPTUyi/view?usp=sharing

And my clover config.plist
https://drive.google.com/file/d/1nJnGDwJr8FGdAxU6B1tnv7AXyx-bSJlM/view?usp=sharing

My installed kexts.
```bash

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
    1   82 0xffffff7f80a46000 0x9d90     0x9d90     com.apple.kpi.bsd (16.7.0) 410B3B98-9DAB-4590-9086-7C57A5B3099A
    2   12 0xffffff7f80e29000 0x3940     0x3940     com.apple.kpi.dsep (16.7.0) FA744B47-913C-4B5D-8C16-2F8005D85935
    3  111 0xffffff7f80a04000 0x21040    0x21040    com.apple.kpi.iokit (16.7.0) 80F2DA67-C67B-4583-9B09-082DB11F69FC
    4  117 0xffffff7f80a26000 0xd200     0xd200     com.apple.kpi.libkern (16.7.0) 370A17F8-C9B7-491A-ACD6-277523ECF3C3
    5  105 0xffffff7f80a00000 0x3dd0     0x3dd0     com.apple.kpi.mach (16.7.0) D88C120B-2055-45F0-B210-8AD0BDE2DEB0
    6   59 0xffffff7f80a34000 0xbbf0     0xbbf0     com.apple.kpi.private (16.7.0) A717B7EC-67D4-4FCC-945E-0F457192AC93
    7   79 0xffffff7f80a40000 0x5890     0x5890     com.apple.kpi.unsupported (16.7.0) BE6C03E4-B6FE-4658-9026-7DED804909B0
    8    6 0xffffff7f80e30000 0xa9000    0xa9000    com.apple.kec.corecrypto (1.0) E3701C61-A548-3181-9F3E-C90DF8327185 <7 6 5 4 3 1>
    9    0 0xffffff7f80f1f000 0xf000     0xf000     com.apple.kec.pthread (1) 225C22A5-813D-3651-9C40-FDEEAB0D78E1 <7 6 5 4 1>
   10    1 0xffffff7f80f55000 0xb000     0xb000     com.apple.kec.Libm (1) 968CBFF1-925D-321E-A5E0-0C5C563BF08C <4>
   11   28 0xffffff7f80f60000 0x9000     0x9000     com.apple.iokit.IOACPIFamily (1.4) 4F7FB6AD-2498-3F71-827C-ED7AA4BF2511 <7 6 4 3>
   12   32 0xffffff7f80b32000 0x3b000    0x3b000    com.apple.iokit.IOPCIFamily (2.9) 3E00E7D2-E569-341D-9BE0-34D5DE491825 <7 6 5 4 3>
   13    2 0xffffff7f83150000 0x66000    0x66000    com.apple.driver.AppleACPIPlatform (5.0) 65E05472-6AE7-3308-8CC8-FA6CB0DB2AEE <12 11 7 6 5 4 3 1>
   14    1 0xffffff7f8121f000 0xb000     0xb000     com.apple.driver.AppleFDEKeyStore (28.30) EA5D0966-E8EA-337A-98EB-195806E8F723 <8 7 6 5 4 3 1>
   15    6 0xffffff7f81750000 0x7000     0x7000     com.apple.iokit.IOReportFamily (31) B14DC3D3-7250-3DA3-BF50-C666EBEDAF4C <5 4 3>
   16    4 0xffffff7f80a50000 0x2f000    0x2f000    com.apple.iokit.IOStorageFamily (2.1) F908D7F5-4F54-3B89-8657-57F06350F4DB <7 6 5 4 3 1>
   17    0 0xffffff7f8184a000 0x1e000    0x1e000    com.apple.driver.DiskImages (444.50.16) 7A04C2E6-40FF-36A9-84D4-FDF685F3B0A9 <16 7 6 5 4 3 1>
   18    1 0xffffff7f80f69000 0xd000     0xd000     com.apple.driver.AppleBusPowerController (1.0) DB526B45-1A45-3A81-A0C1-57F826CADEDF <11 5 4 3>
   19   12 0xffffff7f80f76000 0x71000    0x71000    com.apple.iokit.IOUSBHostFamily (1.1) 896273C6-36AE-30AC-9274-1BCB7C9A4062 <18 7 6 5 4 3 1>
   20    3 0xffffff7f80fe7000 0x21000    0x21000    com.apple.driver.KernelRelayHost (1) DDF94CEB-B30D-3DA9-A783-F86D72A62215 <19 5 4 3>
   21    1 0xffffff7f8290e000 0x25000    0x25000    com.apple.driver.AppleCredentialManager (1.0) 3DC3C93A-F1BC-3B04-B770-B3771039FF0E <20 8 7 6 5 4 3 1>
   22    4 0xffffff7f80ed9000 0x17000    0x17000    com.apple.driver.AppleMobileFileIntegrity (1.0.5) E54425FE-971A-38E2-8F27-82A1B7A3479D <8 7 6 5 4 3 2 1>
   23    0 0xffffff7f82933000 0x55000    0x55000    com.apple.driver.AppleKeyStore (2) 884F9643-4316-3596-9A77-F1053C033358 <22 21 20 8 7 6 5 4 3 1>
   24    0 0xffffff7f83277000 0x4000     0x4000     com.rehabman.driver.USBInjectAll (0.6.1) 4C141052-7721-37C0-874E-4AC05FE917EB <12 11 4 3>
   25    3 0xffffff7f8327c000 0x31000    0x31000    as.vit9696.Lilu (1.1.4) 8706F51C-8552-3987-A50C-721EE1DF34DA <7 5 4 3 2 1>
   26    0 0xffffff7f832ad000 0x3000     0x3000     as.lvs1974.NvidiaGraphicsFixup (1.1.2) F3ADCCD3-50FF-3A62-BB87-422F423678A5 <25 7 5 4 3 2 1>
   27    2 0xffffff7f832b0000 0x19000    0x19000    org.netkas.driver.FakeSMC (1426) 7FA10BCC-EF25-3EAF-A030-E9EA5F78C828 <11 7 5 4 3 1>
   28    0 0xffffff7f832c9000 0x4000     0x4000     org.vanilla.driver.CoreDisplayFixup (1.2.4) 16815EB6-FB7A-3AE3-A5A1-9BC823ADA38C <25 7 5 4 3 2 1>
   29    0 0xffffff7f832cd000 0x9b000    0x9b000    as.vit9696.AppleALC (1.1.2) 6388E0BC-AE43-33C1-8C40-F2189045E584 <25 7 5 4 3 2 1>
   30    0 0xffffff7f83368000 0x9000     0x9000     org.rehabman.driver.AppleSmartBatteryManager (1.70.3) 1A833865-B349-35FA-BD06-8222A4A33CFB <11 4 3>
   31    0 0xffffff7f83374000 0x5000     0x5000     org.hwsensors.driver.CPUSensors (1426) 83AE6ED1-B30C-36F7-8963-718042ECE475 <27 7 5 4 3>
   32    0 0xffffff7f80e2d000 0x2000     0x2000     com.apple.security.TMSafetyNet (8) B87D3377-617E-3F24-993B-D70AE269A837 <7 6 5 4 2 1>
   33    2 0xffffff7f80ef0000 0x5000     0x5000     com.apple.kext.AppleMatch (1.0.0d1) 3B280DAB-903F-33DC-8110-525A1154B11E <4 1>
   34    1 0xffffff7f80ef5000 0x20000    0x20000    com.apple.security.sandbox (300.0) 7AAA3FD3-1652-3365-BCB4-25B9572525AF <33 22 16 7 6 5 4 3 2 1>
   35    0 0xffffff7f80f15000 0x9000     0x9000     com.apple.security.quarantine (3) 1486A49E-2D3F-3D7E-B07A-D2008F327113 <34 33 7 6 5 4 2 1>
   36    0 0xffffff7f8326d000 0x8000     0x8000     com.apple.nke.applicationfirewall (172) 87563A26-608B-3C95-8476-CAA6E1271FBF <7 6 5 4 3 1>
   37    0 0xffffff7f8311e000 0x3000     0x3000     com.apple.driver.AppleAPIC (1.7) BC2E6D01-BCBB-3525-BF38-BF99C3F1EC46 <4 3>
   38    0 0xffffff7f8283d000 0x4000     0x4000     com.apple.driver.AppleSMBIOS (2.1) 9BB02681-4B47-3592-AD62-71FB0BF56965 <7 4 3>
   39   11 0xffffff7f817f2000 0x48000    0x48000    com.apple.iokit.IOGraphicsFamily (515.3) A423518D-758D-3021-A111-A59F44D760A8 <12 7 5 4 3 1>
   40    3 0xffffff7f8183a000 0x10000    0x10000    com.apple.iokit.IONDRVSupport (516.1) 480556A8-289E-3A63-83F8-0E9224255A68 <39 12 7 5 4 3>
   41    4 0xffffff7f81775000 0x1c000    0x1c000    com.apple.driver.AppleSMC (3.1.9) 88026B2E-E18A-3463-97D4-05EE7DED9F06 <12 11 7 5 4 3 1>
   42    1 0xffffff7f83111000 0x5000     0x5000     com.apple.driver.AppleBacklightExpert (1.1.0) 9D276DD1-4746-3504-A9D1-DA189588734D <41 40 39 12 5 4 3>
   43    0 0xffffff7f83116000 0x5000     0x5000     com.apple.driver.AppleBacklight (170.9.20) 2811DFF3-46E3-33C9-9B73-C31A72D6DA02 <42 40 39 12 5 4 3>
   44    0 0xffffff7f82e31000 0x3000     0x3000     com.apple.driver.AppleHPET (1.8) 2CFB49B8-4CC2-320B-9C6E-99646DFD8571 <11 7 5 4 3>
   45    0 0xffffff7f8286a000 0x8000     0x8000     com.apple.driver.AppleRTC (2.0) 3FD1BCF4-8AFC-3CE6-A36E-26410544AD14 <11 5 4 3 1>
   46    1 0xffffff7f817a8000 0x5000     0x5000     com.apple.driver.AppleEFIRuntime (2.1) F1292652-3882-3625-AB38-A0DAB306E9C7 <7 6 5 4 3>
   47    0 0xffffff7f8337c000 0x8000     0x8000     org.hwsensors.driver.ACPISensors (1426) 124B86D8-C096-3745-AD5C-4265C28FA813 <27 11 7 5 4 3>
   48    2 0xffffff7f8338a000 0xb000     0xb000     org.rehabman.voodoo.driver.PS2Controller (1.8.25) 36F84686-25A3-3DD9-86B1-7933D419A4C8 <11 7 5 4 3 1>
   49    6 0xffffff7f8122a000 0x8f000    0x8f000    com.apple.iokit.IOHIDFamily (2.0.0) 6035514B-B403-36FD-BD88-6ADCD3990C9F <14 7 6 5 4 3 2 1>
   50    0 0xffffff7f831c0000 0x4000     0x4000     com.apple.driver.AppleACPIButtons (5.0) 6EA42B65-0CD7-3678-87D5-E002D2CDA2D5 <49 15 13 11 7 6 5 4 3 1>
   51    0 0xffffff7f83395000 0x7000     0x7000     org.rehabman.driver.FakePCIID (1.3.9) BC738576-B800-3E7F-992D-3851C67CCAA9 <12 7 5 4 3 1>
   52    1 0xffffff7f812c4000 0x47000    0x47000    com.apple.driver.usb.AppleUSBXHCI (1.1) 7DBE53B6-8BED-3DD3-984C-7AAAA20C484C <19 11 7 6 5 4 3 1>
   53    0 0xffffff7f8130b000 0x38000    0x38000    com.apple.driver.usb.AppleUSBXHCIPCI (1.1) 65795D1D-0F6C-3648-81CB-8C7CDE52270C <52 19 12 11 7 6 5 4 3 1>
   55    1 0xffffff7f82d8f000 0xa000     0xa000     com.apple.driver.AppleIntelLpssI2C (3.0.60) 0C9DCD18-9FED-363B-9893-C77B876E6063 <12 11 7 5 4 3>
   56    2 0xffffff7f816dc000 0x4000     0x4000     com.apple.iokit.IOSMBusFamily (1.1) 185F0EBF-0262-3370-BD47-8FE4C8AA726E <5 4 3>
   57    0 0xffffff7f831b6000 0x7000     0x7000     com.apple.driver.AppleACPIEC (5.0) C2873EC3-4194-3C09-B16B-FE63BF4C2EAF <56 13 11 5 4 3>
   58    1 0xffffff7f82d49000 0x8000     0x8000     com.apple.driver.AppleIntelLpssDmac (3.0.60) CC87B7B0-B1AB-3084-979F-66967FA9CEF3 <12 11 5 4 3>
   59    0 0xffffff7f82d99000 0x1c000    0x1c000    com.apple.driver.AppleIntelLpssI2CController (3.0.60) D9149887-88AE-32F0-BD7E-2B24F54F1662 <58 55 11 7 5 4 3>
   60    1 0xffffff7f81a72000 0x1d000    0x1d000    com.apple.iokit.IOAHCIFamily (288) 5C275B66-A173-3D92-853A-44FC35D45FFC <5 4 3 1>
   61    0 0xffffff7f83123000 0x1e000    0x1e000    com.apple.driver.AppleAHCIPort (326.60.1) 64D547B5-153B-34CC-B506-10E958212BF6 <60 12 5 4 3 1>
   63    2 0xffffff7f817ad000 0xb000     0xb000     com.apple.driver.AppleEFINVRAM (2.1) 9D230163-2F83-3EAC-9152-D0A15AB056AB <46 7 6 5 4 3 2 1>
   64    2 0xffffff7f81ac5000 0x32000    0x32000    com.apple.driver.corecapture (1.0.4) C269B594-3CE8-3AC8-AC81-ADDCC1C9074A <7 6 5 4 3 1>
   65    4 0xffffff7f810eb000 0x34000    0x34000    com.apple.iokit.IONetworkingFamily (3.2) 6326DB88-5330-3F0C-91F6-D478AB5E7503 <7 6 5 4 3 1>
   66    1 0xffffff7f81af7000 0x8000     0x8000     com.apple.driver.mDNSOffloadUserClient (1.0.1b8) EE4CC064-65B6-3978-9393-C71C74D5BEAA <65 4 3 1>
   67    1 0xffffff7f81aff000 0xf0000    0xf0000    com.apple.iokit.IO80211Family (1200.12.2) 1C010821-6A22-3C8C-B396-409023E8A540 <65 64 22 8 7 6 5 4 3 1>
   68    0 0xffffff7f81bef000 0x7bd000   0x7bd000   com.apple.driver.AirPort.Brcm4360 (1150.12.1a1) BB3626FA-A579-348F-AF69-3249DAC7949D <67 66 65 64 12 7 6 5 4 3 1>
   69    0 0xffffff7f817b8000 0x3a000    0x3a000    com.apple.iokit.IONVMeFamily (2.1.0) 12D4270E-AFFC-34DC-9714-44D1FE33333F <63 22 16 15 12 7 6 5 4 3 1>
   70    0 0xffffff7f833af000 0xd000     0xd000     com.sinet3k.Sinetek-rtsx (1) 61964645-BA77-3017-A03C-DFE13E6AD014 <16 12 7 5 4 3 1>
   71    1 0xffffff7f8115f000 0xac000    0xac000    com.apple.iokit.IOUSBFamily (900.4.1) 1B35F2B8-7EB1-3F3A-86DD-35F07996E335 <19 12 7 5 4 3 1>
   72    0 0xffffff7f8140d000 0x5000     0x5000     com.apple.driver.usb.AppleUSBHostPacketFilter (1.0) 0FEE9916-40A3-3F33-B125-103191A1611A <19 7 6 5 4 3 1>
   74    1 0xffffff7f82431000 0x7000     0x7000     com.apple.filesystems.hfs.encodings.kext (1) 057A044B-8E0D-3A57-8861-87193496E893 <7 6 5 4 3 1>
   75    0 0xffffff7f82438000 0x69000    0x69000    com.apple.filesystems.hfs.kext (366.70.1) B0B8A05A-CC75-325C-A3DA-76C4F7B6F21A <74 7 6 5 4 3 1>
   76    0 0xffffff7f825aa000 0xa000     0xa000     com.apple.BootCache (40) 06D08FFE-3FB9-37A0-A0AE-BDDCDA4184D6 <7 6 5 4 3 1>
   77    0 0xffffff7f830ea000 0x6000     0x6000     com.apple.AppleFSCompression.AppleFSCompressionTypeZlib (1.0.0) A8B584B1-03DF-3780-923B-4FD6FF942049 <6 4 3 2 1>
   78    0 0xffffff7f830f2000 0x3000     0x3000     com.apple.AppleFSCompression.AppleFSCompressionTypeDataless (1.0.0d1) 13DD449C-FA18-3584-92A1-F91CAED7746A <7 6 4 3 2 1>
   80    0 0xffffff7f833bc000 0x7000     0x7000     org.rehabman.voodoo.driver.PS2Keyboard (1.8.25) 11CF4CF1-4DB7-36B3-A022-C8B83D1FEA80 <49 48 15 7 6 5 4 3 1>
   81    0 0xffffff7f833c3000 0xd000     0xd000     org.rehabman.voodoo.driver.PS2Trackpad (1.8.25) 8B46CDD7-DF39-3D34-9FC6-AFBAA57B1CDC <49 48 15 7 6 5 4 3 1>
   83    0 0xffffff7f81416000 0x8000     0x8000     com.apple.driver.usb.AppleUSBHostCompositeDevice (1.1) 93FCA7CE-F6C1-3229-8425-7E4B664231BD <19 5 4 3 1>
   84    0 0xffffff7f82611000 0x8000     0x8000     com.apple.driver.usb.networking (5.0.0) 54F58B56-AFFE-3605-8ADC-E205EAD4D230 <19 5 4 3 1>
   86    1 0xffffff7f833d0000 0x25a000   0x25a000   com.no-one.BrcmFirmwareStore (2.2.7) 160DD596-DFC2-35BD-B0F9-28D95F0B8190 <5 4 3>
   87    0 0xffffff7f8362a000 0x6000     0x6000     com.no-one.BrcmPatchRAM2 (2.2.7) 76FC3024-9FF8-3607-A616-DF7C550751CB <86 19 5 4 3 1>
   88    0 0xffffff7f812b9000 0xb000     0xb000     com.apple.driver.usb.IOUSBHostHIDDevice (1.1) 8C7C5296-D36F-3304-90FE-2A6DD1B0DED8 <49 19 5 4 3 1>
   89    0 0xffffff7f80aef000 0x31000    0x31000    com.apple.iokit.IOSCSIArchitectureModelFamily (394.50.1) 82139727-96EE-3990-B7E3-950D3F9799F5 <6 5 4 3 1>
   90    0 0xffffff7f81440000 0xa000     0xa000     com.apple.iokit.IOUSBHIDDriver (900.4.1) 00FA3E2D-73DB-3778-88DD-681AEB05EF22 <71 49 5 4 3 1>
   91    1 0xffffff7f816e0000 0x5000     0x5000     com.apple.iokit.IOSlowAdaptiveClockingFamily (1.0.0) CE7B6D9D-0577-3683-8410-CA8707BBDA4B <7 6 5 4 3 1>
   92    0 0xffffff7f82995000 0x2000     0x2000     com.apple.driver.AppleIntelSlowAdaptiveClocking (4.0.0) 6FE984DD-A1FE-309E-83CF-B346989A6F17 <91 4 3>
   93    0 0xffffff7f82ded000 0xa000     0xa000     com.apple.driver.AppleHV (1) 86C220DD-F35A-304C-A5AC-35D7EC4FDC90 <7 6 5 4 3 1>
   94    0 0xffffff7f8281e000 0xa000     0xa000     com.apple.driver.AppleSSE (1.0) 56EDE836-9301-3468-8CF7-9FE188EBDC7A <20 7 5 4 3 1>
   95    0 0xffffff7f824a8000 0x5000     0x5000     com.apple.Dont_Steal_Mac_OS_X (7.0.0) 7B7DB739-3DAA-3E7A-BA9E-38C3256D15B6 <41 8 7 4 3 1>
   97    1 0xffffff7f816eb000 0x11000    0x11000    com.apple.iokit.IOSerialFamily (11) 272855EE-C816-329B-927C-383C40F83F1A <7 6 5 4 3 1>
  100    2 0xffffff7f8147b000 0x95000    0x95000    com.apple.vecLib.kext (1.2.0) DDD8F03B-087A-3709-8296-354CCE62BE15 <10 6 5 4 3>
  101    4 0xffffff7f81510000 0x47000    0x47000    com.apple.iokit.IOAudioFamily (205.15) 2D3115C6-0FFD-3244-AB4A-4F9041C5D614 <100 5 4 3 1>
  102    2 0xffffff7f82e4c000 0xf000     0xf000     com.apple.iokit.IOHDAFamily (279.48) E332A19C-33F1-3F25-B9FC-982F769BF17A <5 4 3 1>
  103    1 0xffffff7f82e5f000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (279.48) ED51F180-19C8-3DE1-AF81-0E389D98ADDE <102 101 39 12 7 6 5 4 3 1>
  104    2 0xffffff7f82999000 0x9f000    0x9f000    com.apple.iokit.IOAcceleratorFamily2 (311.14) 13F71024-7246-3AD1-A551-5C186BC70889 <39 12 7 6 5 4 3 1>
  105    1 0xffffff7f82a38000 0xc000     0xc000     com.apple.AppleGraphicsDeviceControl (3.14.49) FA94C7C0-04C2-3F83-9F96-0470C31E2AA3 <7 6 5 4 3 1>
  106    0 0xffffff7f82a44000 0x1cb000   0x1cb000   com.apple.driver.AppleIntelSKLGraphicsFramebuffer (10.2.5) 593CB673-AD1F-39AC-8D89-175516FC7BC8 <105 104 39 15 12 11 7 6 5 4 3 1>
  107    0 0xffffff7f828c2000 0x4000     0x4000     com.apple.driver.AppleOSXWatchdog (1) 9B1AC3B0-A459-3D88-B43D-428EA39DDB8A <12 7 6 5 4 3 1>
  109    3 0xffffff7f818ee000 0xf8000    0xf8000    com.apple.iokit.IOBluetoothFamily (5.0.5f1) 5AA0EAB8-6128-3B0C-B8CE-293BDB9D21A8 <15 7 5 4 3 1>
  110    0 0xffffff7f82828000 0x3000     0x3000     com.apple.driver.AppleSMBusPCI (1.0.14d1) 336ED4BC-E18C-37EE-A185-CD41B0819BC9 <12 5 4 3>
  111    1 0xffffff7f816c2000 0x1a000    0x1a000    com.apple.iokit.IOSurface (159.9) 24A912F5-68C5-3BF9-9676-4FB131A6E90C <7 6 5 4 3 1>
  112    0 0xffffff7f82c39000 0xc6000    0xc6000    com.apple.driver.AppleIntelSKLGraphics (10.2.5) 1558E58D-2CD5-396C-BFDB-B52FAA939D8C <111 104 39 12 7 6 5 4 3 1>
  113    0 0xffffff7f818da000 0xa000     0xa000     com.apple.iokit.IOBluetoothSerialManager (5.0.5f1) 28B1B6A7-E5CD-3C1A-B337-DD81C3A2CE01 <97 7 5 4 3 1>
  114    0 0xffffff7f8111f000 0x6000     0x6000     com.apple.iokit.IOUserEthernet (1.0.1) 32E2019A-799D-3E86-9F40-7D9AB4500A9D <65 6 5 4 3 1>
  115    0 0xffffff7f80f2e000 0xf000     0xf000     com.apple.driver.pmtelemetry (1) 48FE4CE8-66CC-335E-9ABD-835F954B114D <7 6 5 4 3>
  116    4 0xffffff7f81757000 0xa000     0xa000     com.apple.driver.IOPlatformPluginFamily (6.0.0d8) A578127A-BBAD-32D4-AEBD-20E14786110D <11 7 6 5 4 3>
  117    0 0xffffff7f82d44000 0x3000     0x3000     com.apple.driver.AppleIntelPCHPMC (1.1) E7CFE09B-8A79-3A2C-A942-43F81011A557 <116 12 5 4 3>
  118    0 0xffffff7f82909000 0x3000     0x3000     com.apple.driver.AppleLPC (3.1) F51595F0-F9B1-3B85-A1C3-F984DAD4107E <116 12 5 4 3>
  119    1 0xffffff7f8282b000 0x12000    0x12000    com.apple.driver.AppleSMBusController (1.0.18d1) C0F713E6-785F-3BC6-8800-1D6E2C7AE123 <56 12 11 5 4 3>
  120    1 0xffffff7f82e7c000 0x13000    0x13000    com.apple.kext.OSvKernDSPLib (525) D0421B4D-7B97-3102-BC42-3684344DB5E6 <5 4>
  121    1 0xffffff7f82e8f000 0x152000   0x152000   com.apple.driver.DspFuncLib (279.48) F6771373-D27C-36AA-B87E-5038F235C536 <120 101 100 63 6 5 4 3 1>
  122    0 0xffffff7f82fe1000 0xb5000    0xb5000    com.apple.driver.AppleHDA (279.48) 806B8C17-50CA-3C6B-90B3-195F38D8FB89 <121 103 102 101 40 39 6 5 4 3 1>
  124    0 0xffffff7f828cf000 0xe000     0xe000     com.apple.driver.AppleMCCSControl (1.3.4) BF69780E-2728-34A8-A5B9-59290572CCF3 <119 41 39 12 11 7 5 4 3 1>
  125    0 0xffffff7f8267a000 0x5000     0x5000     com.apple.driver.AppleUpstreamUserClient (3.6.4) F39509A4-191C-35DA-B7D9-08F95E5AB8BC <39 12 11 7 5 4 3 1>
  126    1 0xffffff7f81761000 0x14000    0x14000    com.apple.driver.IOPlatformPluginLegacy (1.0.0) BC0876C4-ED42-31B7-AF69-9178B7B1177A <116 11 7 6 5 4 3>
  127    0 0xffffff7f81791000 0x10000    0x10000    com.apple.driver.ACPI_SMC_PlatformPlugin (1.0.0) 5D441A20-E42C-313C-BF80-6894AAAE0DFA <126 116 41 12 11 7 6 5 4 3>
  129    2 0xffffff7f819e6000 0xb000     0xb000     com.apple.iokit.IOBluetoothHostControllerTransport (5.0.5f1) DAC3389D-A9B3-3E1E-8D1E-8D72CE96BBC1 <109 19 12 11 7 6 5 4 3 1>
  130    1 0xffffff7f819f1000 0x23000    0x23000    com.apple.iokit.IOBluetoothHostControllerUSBTransport (5.0.5f1) 98323CF2-1639-3312-A334-0E82F99359D3 <129 109 19 12 11 7 6 5 4 3 1>
  131    0 0xffffff7f81a14000 0xc000     0xc000     com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport (5.0.5f1) 9A285F2F-102C-3D4C-9556-CB8545EBA4DC <130 129 109 19 12 11 7 6 5 4 3>
  132    0 0xffffff7f825c6000 0x5000     0x5000     com.apple.driver.AudioAUUC (1.70) DA1CA792-7C22-3F41-B64E-4E01C8679031 <101 39 12 11 7 5 4 3 1>
  133    1 0xffffff7f825b6000 0x5000     0x5000     com.apple.kext.triggers (1.0) 3EAB29BE-4C7C-3D6C-B20B-B48707426005 <7 6 5 4 3 1>
  134    0 0xffffff7f825bb000 0x9000     0x9000     com.apple.filesystems.autofs (3.0) E79E1801-8AB8-3BB1-A1F2-3CA5F9C7C648 <133 7 6 5 4 3 1>
  135    0 0xffffff7f83630000 0x1d000    0x1d000    com.intel.kext.intelhaxm (6.2.1) 7B6ABC56-699C-3449-A0EC-BEB36C154E3C <7 5 4 3 1>
  136    0 0xffffff7f8364d000 0x7000     0x7000     org.pqrs.driver.Karabiner.VirtualHIDDevice.v041100 (4.11.0) E1649988-9411-3099-82B6-131B2B52A2DE <49 5 4 3 1>
```

**Comment by Hammief** [comment]
When I switched from WMChris's config.plist to darkhandz and change the ig-platform-id from 0x191B0000 to 0x19160000, the screen flickering did reduce quite a lot in severity. It's still there, but not the whole turning off anymore like in @jhlee8804 's vid. 

Could it be that the SMBIOS is partly at blame? I went from the iMac 5k to darkhandz plist (which is MacBook Pro '16) and it did reduce.

Specs:
i7 6700HQ
16GB RAM
macOS 10.13.2
Intel HD Graphics 530
Hynix SSD (with patch from rehabman)
BIOS 1.5.1

edit 1: seems to be gone entirely, going to test it in the following days. Also added specs.
edit 2: screen flickering is gone by 99%. Maybe once daily, I see some small green lines for 1-3 seconds max.

**Comment by liamsheppard** [comment]
I had an issue with my display turning off completely. I found that it was nothing to do with OSX/Hackintosh, it's actually a hardware problem, and unrelated to the artefacts showing after it wakes up from sleep (That still happens). I actually found a bunch of examples of the exact same thing happening on Windows 10.

**For reference, here's what the symptoms of my display turning off were:**
- White horizontal 1px lines randomly appearing on the screen
- Display turning off for 1 second to indefinitely (I used to be able to reboot it or just leave it for a few hours and the display would work again, until it got to a point when the display just didn't turn on)
- While the display is off, any external monitors still work as expected, and you can see that the laptop is working completely normal, except for the display not working.
- Keyboard light still works, and sound still plays.

**How I fixed it:**
_Note that this isn't a fix for artefacts showing up after sleep, this is a fix for your display shutting off_
I reseated the display connector
- Took off the backplate, to do this you need: 
  - A Torx T5 bit (looks like a star)
  - A 2mm phillips screwdriver
  - [Here's the XPS9550 Service Manual, you'll want p12](http://topics-cdn.dell.com/pdf/xps-15-9550-laptop_service%20manual_en-us.pdf)
- The display connector is under this plate:
![image](https://user-images.githubusercontent.com/15017759/34852142-e6a3909a-f778-11e7-96da-b93c5f92f8e2.png)
I just wiggled the connector a bit then pushed it back in, I also put a few layers of electrical tape onto the plate just to give it a bit less wiggle room.

This fixed mine, but your mileage may vary.

**Comment by soulomoon** [comment]
@Hammief 
Glad to know that the solution is working for you, could you provide your bios version too just for statistic. Because the solution does not seem to work for everyone, somehow I think it has something to do with bios, though I am not technically capable enough of finding out the real reason

**Comment by Hammief** [comment]
@soulomoon I've added it! Let me know if you need any more help to solve this issue!

**Comment by HeavenVolkoff** [comment]
@soulomoon @wmchris

I finally had some time to do a full reinstall of my XPS and updated all my configs as well as tried using the `platform-id 0x19160000`. I can confirm that it significantly reduced the amount of white line artifacts and completely removed the flicker present after turning off the computer's screen. There are still some random moments when the screen flicks off and on but those occurs rarely and on a full day use with lots of sleep moments it only happened three times. However I only archived this after injecting the `platform-id` in the `ACPI\patched\SSDT-CONFIG.aml` file, because changing only on `config.plist` didn't solved anything.

Thank you very much @soulomoon for finding this solution, now I finally have a fully functional hackintosh.

Edit: Sorry about the repeated messages, my github app bugged hard XD

**Comment by HeavenVolkoff** [comment]
@soulomoon @wmchris

I finally had some time to do a full reinstall of my XPS and updated all my configs as well as tried using the `platform-id 0x19160000`. I can confirm that it significantly reduced the amount of white line artifacts and completely removed the flicker present after turning off the computer's screen. There are still some random moments when the screen flicks on and off but those occurs rarely and on a full day use with lots of sleep moments it only happened three times. However I only archived this after injecting the `platform-id` in the `ACPI\patched\SSDT-CONFIG.aml` file, because changing only on `config.plist` didn't solved anything.

Thank you very much @soulomoon for finding this solution, now I finally have a fully functional hackintosh.

**Comment by HeavenVolkoff** [comment]
@soulomoon @wmchris

I finally had some time to do a full reinstall of my XPS and updated all my configs as well as tried using the `platform-id 0x19160000`. I can confirm that it significantly reduced the amount of white line artifacts and completely removed the flicker present after turning off the computer's screen. There are still some random moments when the screen flicks on and off but those occurs rarely and on a full day use with lots of sleep moments it only happened three times. However I only archived this after injecting the `platform-id` in the `ACPI\patched\SSDT-CONFIG.aml` file, because changing only on `config.plist` didn't solved anything.

Thank you very much @soulomoon for finding this solution, now I finally have a fully functional hackintosh.

**Comment by HeavenVolkoff** [comment]
@soulomoon @wmchris

I finally had some time to do a full reinstall of my XPS and updated all my configs as well as tried using the `platform-id 0x19160000`. I can confirm that it significantly reduced the amount of white line artifacts and completely removed the flicker present after turning off the computer's screen. There are still some random moments when the screen flicks on and off but those occurs rarely and on a full day use with lots of sleep moments it only happened three times. However I only archived this after injecting the `platform-id` in the `ACPI\patched\SSDT-CONFIG.aml` file, because changing only on `config.plist` didn't solved anything.

Thank you very much @soulomoon for finding this solution, now I finally have a fully functional
##  hackintosh.

**Comment by ghsssss** [comment]
https://github.com/yaozaiyu/tutorial 
sry,My mother tongue is not English.You can take a look at my tutorial to see if I can solve the problem.

**Comment by krim404** [comment]
seems like the issue is fixed by injecting the edid. got some positive feedback. I added the step by step tutorial to the git and close this issue

**Comment by mrhuy92** [comment]
I had same problem, tried ig-platform-id 19160000, patch edid,... but not solved.

**Comment by heyhwi** [comment]
I have the same problem too, with 4K screen and 10.15.2. I've already tried both two method metioned above but didn't work.

**Comment by krim404** [comment]
did you try to reseat the connector?

**Comment by mrhuy92** [comment]
> did you try to reseat the connector?

It isn't happen in windows. It only happen when screen turn off and turn on again.

**Comment by heyhwi** [comment]
> I had same problem, tried ig-platform-id 19160000, patch edid,... but not solved.

Maybe it’s because of Catalina? All these solutions were proposed long time ago.. Are you using Catalina?

**Comment by golimpio** [comment]
I can confirm that there is a bit of flicker on Catalina with 4k screen (i7). It happens a few time during the day. It's annoying, but since it's not too much (around 10 per hour), it's fine for now. I haven't tried 19160000 though. I'm running on the latest BIOS and 10.15.3.
